### PR TITLE
Remove Materializer constraint from AkkaStreamCursor.*Source api.

### PR DESCRIPTION
**Pull request by jbgi**
Instead use the execution context provided when the source is "run",
ie. via the GraphStage api.

This make the api more useful for cases were you don't have a Materializer at hand, and match akka-stream users expectation that `Source`s are "blue prints" and the `Materializer` in only needed/provided via the `run`* methods.

### CODE REVIEW

**Comment by cchantep** [comment]
Hi, 

Thanks for your contribution. As that's a design change a prior discussion would be nice.
There I'm not sure to agree to the fact that the `Materializer` and `ExecutionContext` are no longer resolved from the implicit scope, respecting the choice of the developer.

**Comment by jbgi** [comment]
Well it is still resolve implicitly to a Materializer provided by the user, via the `run*` methods of the `Source` api.

**Comment by cchantep** [comment]
These changes are unfortunately breaking the [API compatibility](https://travis-ci.org/ReactiveMongo/ReactiveMongo-Streaming/jobs/186218444#L371), so it cannot be accepted as-is. Keep the existing functions as deprecated and adding new functions is the only way it could be validated. Best regards.

**Comment by jbgi** [comment]
Thanks for your feedback, it is indeed a breaking change. Apart from finding new function names (which I have trouble finding non-ugly ones) I can see two other strategies to preserve binary compatibility:

1. introduce a new namespace: eg. `reactivemongo.akkastream.cursor`. user will just have to change the import to use the api without the implicit Materializer.
2. introduce the breaking change only in the 2.12 build: it has never been released and is binary incompatible anyway.

@cchantep WDYT?

**Comment by jbgi** [comment]
I'm starting to think the change is not worse the hassle: you usually get an `AkkaStreamCursor` right from a newly created `Cursor` in the first place, which require an `ExecutionContext` for it creation. So having a `Materializer` constraint is not much more than what one already need in scope.
Removing the constraint would be nice but it not that important.

So feel free to close this PR. or maybe just consider the minor implementation changes in `AkkaStreamFlattenedCursor` which allow to avoid one `map`.

**Comment by cchantep** [comment]
Will keep it open some times, if have time to have a look at the deprecation cost. Best regards and thanks for your contribution.

**Pull request closed without merging**
